### ISSUE TITLE
0.6.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [ilevkivskyi/typing_inspect#70]
```
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing typing_inspect.egg-info/PKG-INFO
writing dependency_links to typing_inspect.egg-info/dependency_links.txt
writing requirements to typing_inspect.egg-info/requires.txt
writing top-level names to typing_inspect.egg-info/top_level.txt
reading manifest file 'typing_inspect.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'typing_inspect.egg-info/SOURCES.txt'
running build_ext
test_typing_inspect (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_typing_inspect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_typing_inspect
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/typing_inspect-0.6.0/typing_inspect.py", line 29, in <module>
    from typing import _SpecialGenericAlias
ImportError: cannot import name '_SpecialGenericAlias' from 'typing' (/usr/lib64/python3.8/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/tkloczko/rpmbuild/BUILD/typing_inspect-0.6.0/test_typing_inspect.py", line 2, in <module>
    from typing_inspect import (
  File "/home/tkloczko/rpmbuild/BUILD/typing_inspect-0.6.0/typing_inspect.py", line 30, in <module>
    except ImportErrror:
NameError: name 'ImportErrror' is not defined


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by JelleZijlstra** [comment]
`ImportErrror` (with three rs) doesn't appear in the repo right now, nor in the code as of the 0.6.0 release (https://github.com/ilevkivskyi/typing_inspect/blob/8e1a73f3cf0dab287460752bc5c4e4d888397af9/typing_inspect.py). Where did you get the code from?

**Comment by kloczek** [comment]
Closing.
Looks like latest version is OK now.
